Repository PickwickSoft/libraary, pull requests merged in 2022-09, with the labels that each got.

#3 Fix content security policy
  src/main/resources/config/application.yml
Labels: bug

#7 Redesign password reset and enhance login components
  src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html
  src/main/webapp/app/account/password-reset/init/password-reset-init.component.html
  src/main/webapp/app/login/login.component.html
Labels: enhancement, frontend

#8 Implement Mailgun EMail sender
  src/main/java/org/pickwicksoft/libraary/config/MailConfig.java
  src/main/resources/config/application-dev.yml
Labels: enhancement, backend

#10 Fix issues in Mailsender config
  src/main/resources/config/application-prod.yml
  src/test/resources/config/application.yml
Labels: bug, backend

#11 Backend tests
  .github/workflows/test-backend.yml
  README.md
  src/main/java/org/pickwicksoft/libraary/domain/Address.java
  src/main/java/org/pickwicksoft/libraary/web/rest/CategoryResource.java
  src/test/java/org/pickwicksoft/libraary/web/rest/CategoryResourceIT.java
  src/test/java/org/pickwicksoft/libraary/web/rest/SubCategoryResourceIT.java
Labels: bug, backend

#12 Ng dialog impl
  src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html
  src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.ts
  src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts
  src/main/webapp/app/admin/user-management/list/user-management.component.ts
  src/main/webapp/app/shared/dialog/mat-dialog.service.ts
  src/main/webapp/i18n/en/user-management.json
Labels: enhancement, frontend
